Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/usr/local/lib/python3.8/dist-packages/nbclient/client.py", line 1112, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/usr/local/lib/python3.8/dist-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/usr/local/lib/python3.8/dist-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.8/dist-packages/nbclient/client.py", line 553, in async_execute
    await self.async_execute_cell(
  File "/usr/local/lib/python3.8/dist-packages/nbclient/client.py", line 857, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/usr/local/lib/python3.8/dist-packages/nbclient/client.py", line 760, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
data_availability(mission='PAMARCMiP', platform='P6')
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mKeyError[0m                                  Traceback (most recent call last)
[0;32m/tmp/ipykernel_594576/3170661857.py[0m in [0;36m<module>[0;34m[0m
[0;32m----> 1[0;31m [0mdata_availability[0m[0;34m([0m[0mmission[0m[0;34m=[0m[0;34m'PAMARCMiP'[0m[0;34m,[0m [0mplatform[0m[0;34m=[0m[0;34m'P6'[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m
[0;32m/tmp/ipykernel_594576/717516275.py[0m in [0;36mdata_availability[0;34m(mission, platform)[0m
[1;32m     20[0m     [0;31m# store data availability in a matrix[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m
[1;32m     21[0m     data_availability = np.zeros(shape=(len(list(cat[mission][platform])),
[0;32m---> 22[0;31m                                         len(list(meta[mission][platform]))))
[0m[1;32m     23[0m     [0;32mfor[0m [0mi[0m[0;34m,[0m [0mdataset[0m [0;32min[0m [0menumerate[0m[0;34m([0m[0mlist[0m[0;34m([0m[0mcat[0m[0;34m[[0m[0mmission[0m[0;34m][0m[0;34m[[0m[0mplatform[0m[0;34m][0m[0;34m)[0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m     24[0m         data_availability[i, :] = np.isin(list(meta[mission][platform]), 

[0;31mKeyError[0m: 'P6'
KeyError: 'P6'

