Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/usr/local/lib/python3.8/dist-packages/nbclient/client.py", line 1112, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/usr/local/lib/python3.8/dist-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/usr/local/lib/python3.8/dist-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.8/dist-packages/nbclient/client.py", line 553, in async_execute
    await self.async_execute_cell(
  File "/usr/local/lib/python3.8/dist-packages/nbclient/client.py", line 857, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/usr/local/lib/python3.8/dist-packages/nbclient/client.py", line 760, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
ds_dict = {'ACLOUD': {}, 'AFLUX': {}, 'MOSAiC-ACA': {}}
for campaign in meta.values():
    for platform in campaign.values():
        for flight in platform.values():
            for segment in flight['segments']:
                if 'dropsondes' in segment.keys() and segment['dropsondes']:
                    for sonde in segment['dropsondes']:
                        params = {'segment_id': segment['segment_id'],
                                  'flight_id': flight['flight_id'],
                                  'date': flight['date'],
                                  'name': flight['name'],
                                 }
                        ds_dict[flight['mission']][sonde] = params
                        print(sonde)
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mKeyError[0m                                  Traceback (most recent call last)
[0;32m/tmp/ipykernel_933370/323801545.py[0m in [0;36m<module>[0;34m[0m
[1;32m     11[0m                                   [0;34m'name'[0m[0;34m:[0m [0mflight[0m[0;34m[[0m[0;34m'name'[0m[0;34m][0m[0;34m,[0m[0;34m[0m[0;34m[0m[0m
[1;32m     12[0m                                  }
[0;32m---> 13[0;31m                         [0mds_dict[0m[0;34m[[0m[0mflight[0m[0;34m[[0m[0;34m'mission'[0m[0;34m][0m[0;34m][0m[0;34m[[0m[0msonde[0m[0;34m][0m [0;34m=[0m [0mparams[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m     14[0m                         [0mprint[0m[0;34m([0m[0msonde[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;31mKeyError[0m: 'HALO-AC3'
KeyError: 'HALO-AC3'

