Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/usr/local/lib/python3.8/dist-packages/nbclient/client.py", line 1112, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/usr/local/lib/python3.8/dist-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/usr/local/lib/python3.8/dist-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.8/dist-packages/nbclient/client.py", line 553, in async_execute
    await self.async_execute_cell(
  File "/usr/local/lib/python3.8/dist-packages/nbclient/client.py", line 857, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/usr/local/lib/python3.8/dist-packages/nbclient/client.py", line 760, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
fig, axes = plt.subplots(1, 3, sharey=True, sharex=True)

ax = {'ACLOUD': axes[0], 'AFLUX': axes[1], 'MOSAiC-ACA': axes[2]}

kwargs = dict(s=1, color='red', alpha=0.4)
for mission, sondes in ds_dict.items():
    
    if mission != 'HALO-AC3':
        ax[mission].set_title(mission)

        for sonde_id, params in ds_dict[mission].items():

            # read dropsonde data
            i_sonde = int(sonde_id[-2:])
            ds = cat[mission]['P5']['DROPSONDES'][params['flight_id']](i_sonde=i_sonde).to_dask()

            ax[mission].scatter(ds.Temp_recon, ds.GPS_Alt, **kwargs)

axes[0].set_ylabel('Altitude [m]')
axes[0].set_xlabel('Temperature [Â°C]')
   
plt.show()
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mKeyError[0m                                  Traceback (most recent call last)
[0;32m/tmp/ipykernel_3105331/4146597178.py[0m in [0;36m<module>[0;34m[0m
[1;32m     13[0m             [0;31m# read dropsonde data[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m
[1;32m     14[0m             [0mi_sonde[0m [0;34m=[0m [0mint[0m[0;34m([0m[0msonde_id[0m[0;34m[[0m[0;34m-[0m[0;36m2[0m[0;34m:[0m[0;34m][0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0;32m---> 15[0;31m             [0mds[0m [0;34m=[0m [0mcat[0m[0;34m[[0m[0mmission[0m[0;34m][0m[0;34m[[0m[0;34m'P5'[0m[0;34m][0m[0;34m[[0m[0;34m'DROPSONDES'[0m[0;34m][0m[0;34m[[0m[0mparams[0m[0;34m[[0m[0;34m'flight_id'[0m[0;34m][0m[0;34m][0m[0;34m([0m[0mi_sonde[0m[0;34m=[0m[0mi_sonde[0m[0;34m)[0m[0;34m.[0m[0mto_dask[0m[0;34m([0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m     16[0m [0;34m[0m[0m
[1;32m     17[0m             [0max[0m[0;34m[[0m[0mmission[0m[0;34m][0m[0;34m.[0m[0mscatter[0m[0;34m([0m[0mds[0m[0;34m.[0m[0mTemp_recon[0m[0;34m,[0m [0mds[0m[0;34m.[0m[0mGPS_Alt[0m[0;34m,[0m [0;34m**[0m[0mkwargs[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;32m/usr/local/lib/python3.8/dist-packages/intake/catalog/base.py[0m in [0;36m__getitem__[0;34m(self, key)[0m
[1;32m    408[0m                 [0mout[0m [0;34m=[0m [0mself[0m[0;34m[[0m[0mpart[0m[0;34m][0m[0;34m[0m[0;34m[0m[0m
[1;32m    409[0m             [0;32mreturn[0m [0mout[0m[0;34m([0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 410[0;31m         [0;32mraise[0m [0mKeyError[0m[0;34m([0m[0mkey[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    411[0m [0;34m[0m[0m
[1;32m    412[0m     [0;32mdef[0m [0mdiscover[0m[0;34m([0m[0mself[0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m

[0;31mKeyError[0m: 'ACLOUD_P6_RF10'
KeyError: 'ACLOUD_P6_RF10'

