Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/usr/local/lib/python3.8/dist-packages/nbclient/client.py", line 1112, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/usr/local/lib/python3.8/dist-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/usr/local/lib/python3.8/dist-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.8/dist-packages/nbclient/client.py", line 553, in async_execute
    await self.async_execute_cell(
  File "/usr/local/lib/python3.8/dist-packages/nbclient/client.py", line 857, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/usr/local/lib/python3.8/dist-packages/nbclient/client.py", line 760, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
cat = ac3airborne.get_intake_catalog()

datasets = []
for campaign in ['ACLOUD']:
    datasets.extend(list(cat[campaign]['P6']['OPC']))
datasets
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mKeyError[0m                                  Traceback (most recent call last)
[0;32m/tmp/ipykernel_2973249/744211412.py[0m in [0;36m<module>[0;34m[0m
[1;32m      3[0m [0mdatasets[0m [0;34m=[0m [0;34m[[0m[0;34m][0m[0;34m[0m[0;34m[0m[0m
[1;32m      4[0m [0;32mfor[0m [0mcampaign[0m [0;32min[0m [0;34m[[0m[0;34m'ACLOUD'[0m[0;34m][0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m----> 5[0;31m     [0mdatasets[0m[0;34m.[0m[0mextend[0m[0;34m([0m[0mlist[0m[0;34m([0m[0mcat[0m[0;34m[[0m[0mcampaign[0m[0;34m][0m[0;34m[[0m[0;34m'P6'[0m[0;34m][0m[0;34m[[0m[0;34m'OPC'[0m[0;34m][0m[0;34m)[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m      6[0m [0mdatasets[0m[0;34m[0m[0;34m[0m[0m

[0;32m/usr/local/lib/python3.8/dist-packages/intake/catalog/base.py[0m in [0;36m__getitem__[0;34m(self, key)[0m
[1;32m    408[0m                 [0mout[0m [0;34m=[0m [0mself[0m[0;34m[[0m[0mpart[0m[0;34m][0m[0;34m[0m[0;34m[0m[0m
[1;32m    409[0m             [0;32mreturn[0m [0mout[0m[0;34m([0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 410[0;31m         [0;32mraise[0m [0mKeyError[0m[0;34m([0m[0mkey[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    411[0m [0;34m[0m[0m
[1;32m    412[0m     [0;32mdef[0m [0mdiscover[0m[0;34m([0m[0mself[0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m

[0;31mKeyError[0m: 'OPC'
KeyError: 'OPC'

